---
version: '3.7'
services:
  web_test:
    build: .
    command: make start
    depends_on:
      - db_test
    tty: true
    volumes:
      - .:/code
    container_name: ls_test

  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
    container_name: db_test
