---
version: '3.7'
services:
  web_test:
    build: .
    command: make test-coverage
    depends_on:
      - db_test
    tty: true
    volumes:
      - .:/code
    container_name: ls_test
    environment:
    - GH_CLIENT_ID
    - GH_CLIENT_SECRET
    - HOST
    - TOKEN_SECRET

  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
    container_name: db_test
